language: node_js
node_js:
- node
install:
- pushd ./guide
- npm install
- popd
script:
- pushd ./guide
- npm run build
- popd
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./guide/dist
  name: Travis CI
  on:
    branch: master
env:
  global:
  - secure: aF+MXekl56nqNktKzEzhB1Q0WhAggbQFT63wSt97ZwfnN27xgLCyWQGPQwFO65dqcq9W8m0Wlkg1imqM0PTUc4QqdKs7xpKGqRchC6hiVGa6udLWlNz6EPiWC4Hl+eBA2RP1Kg/0e+/GvUtbdgNMYGuXA3h7MfwoY3QfCXNCre7UEPSgUBLYx6DvFykhinbc3WnCa6Wg3TyPqLQtjZWUaUbAUlqgvSvO0lOEdpJt9FVKp1Uoy6FQXzy/SLofJxoVknI1QWKA2CtRxzg4sM9Em9CwgAtbwk+kauZeQuhJ1aCAg7MA0syOnJLciBhY6+FORe/cIWhqnBy7b3Teay7WM6P22055XIL868xsZWF4K8jPku8dve50oy/0KN/+bk5+w1NY8YTJXwH0OFgkMWQFtlM/nz0UMf/Pq9kdsJSQiY0KMjP+ThEXhspsqqaWMNO8vC+Qt6wNpUWXiY90M5OgUCG3AmmwbS+abF6IgH3cDXWm8YrD054Oz2g/FodH77Cae3/q2tI2CBwkKTc6tBzQO6lJEMz9K+UIGoT2ZjcLJufU223M/Hac17nYTv4MiH2hehmDQWGQkm97T1z0bFFUPDOPtPSw7EBfNhvuIPhVElBk4ek99D1MyDx1R9eR/lu1sxnc4WrtP5Rmwl3xYmfoM7H0GHmQbg+OHtFf5jMIvKE=
  - secure: thz8brNDEZfH2duiHlBdpPXg6TwO2iEiZKpl/909fqSMDCod1n91nXFkmWPPk1sIwjSeFF9eNARzo/zVf2eUvC0kz0F2dgQX3XIukh4qqzIs/VjGIBn1qYLPKOmmvEI3gKkWQA7VaC4AMpU8K41rewPuLZd7UNJuK8AwW8lkgxE0t5Q4WNGbK30VfzcXu5NOD6YZEFtPcc6V1Os8USMTPXQRt0i+/rlzVVoJ6Eu56/xrFfnTP5MThBf1rdYBA8R379/U30rBKpkw0Ps658srgiIoHwnddrnSA/9+h65l3x6xz2AGjABRq3M7B3Ohk5KmxZvwL5jRXLOZGyliwuRzx/evH9rikw97q3MOQOngNOSHXkpgXDaYgWLDUlb+jAsqbrDnw1UHlcNcB7/i/SE1Dqjl9OG8yI+elGv5eT+/L91R7LyCqNJLFUPdIqQppr3keVhigZGT0HeoogaxxzgV0iwWdekr0e/LfBTWNjr8MhYJ6is8Zh04KVAJLSMprqa4QKyHif8mU240/FTb8GSCnQZ2BzZL5pz+mi6FToB7tHkpvkjQ5lWx7ab12LOBrL7T4KquBnM3cVCZI/ePABi1ss2ghY4AXeGgvIwBOnai2K+exSXRlHZMN9fVbIERHtOfO5At+ubfDH82EhTraPsjqlA6aV7Irtqt8mOxTyZRwoc=
